In [61]:
import pandas as pd 
import numpy as np
from datetime import datetime,timedelta

np.random.seed(10)

# Customer.csv

In [62]:
num_customers = 5000

customer = pd.DataFrame({
    "customer_id" : [f"C{i:05d}" for i in range(1,num_customers+1)],
    "first_name" : np.random.choice(
        ["Mohammed", "John", "Sara", "David", "Ali",
         "Aisha", "Fatima", "Omar", "Daniel", "Emma"],num_customers),
    "gender" : np.random.choice(
        ["Male","Female"],num_customers),
    "age" : np.random.randint(18,65,num_customers),
    "city" : np.random.choice(
        ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain"],
        num_customers,
        p = [0.40,0.25,0.20,0.10,0.05])
})

In [63]:
customer.head()

  customer_id first_name  gender  age       city
0      C00001       Emma  Female   44  Abu Dhabi
1      C00002        Ali    Male   41  Abu Dhabi
2      C00003   Mohammed  Female   33      Dubai
3      C00004       John    Male   46  Abu Dhabi
4      C00005       Emma  Female   62  Abu Dhabi

In [64]:
customer["country"] = "UAE"

In [65]:
customer.head()

  customer_id first_name  gender  age       city country
0      C00001       Emma  Female   44  Abu Dhabi     UAE
1      C00002        Ali    Male   41  Abu Dhabi     UAE
2      C00003   Mohammed  Female   33      Dubai     UAE
3      C00004       John    Male   46  Abu Dhabi     UAE
4      C00005       Emma  Female   62  Abu Dhabi     UAE

In [66]:
start_date = pd.Timestamp("2024-01-01")
end_date = pd.Timestamp("2026-06-30")

customer["signup_date"] = pd.to_datetime(
    np.random.randint(
        start_date.value // 10**9,
        end_date.value // 10**9,
        num_customers
    ),
    unit = "s"
)

In [67]:
customer.head()

  customer_id first_name  gender  age       city country         signup_date
0      C00001       Emma  Female   44  Abu Dhabi     UAE 2025-12-29 22:58:08
1      C00002        Ali    Male   41  Abu Dhabi     UAE 2026-03-16 23:32:50
2      C00003   Mohammed  Female   33      Dubai     UAE 2026-06-17 00:37:09
3      C00004       John    Male   46  Abu Dhabi     UAE 2024-07-22 10:53:18
4      C00005       Emma  Female   62  Abu Dhabi     UAE 2026-06-26 10:01:17

# customer.to_csv(
    "../data/raw/customer.csv",
    index = False
)

# Products.csv

In [68]:
num_products  = 500

categories = {
    "Electronics": ["Headphones", "Smartphones", "Laptops", "Accessories"],
    "Fashion": ["Shoes", "Clothing", "Bags", "Watches"],
    "Home": ["Furniture", "Kitchen", "Decor", "Lighting"],
    "Beauty": ["Skincare", "Makeup", "Haircare", "Fragrance"],
    "Sports": ["Fitness", "Outdoor", "Sportswear", "Equipment"]
}

In [69]:
product_rows = []

for i in range(1,num_products + 1):

    category = np.random.choice(
        list(categories.keys())
    )

    sub_category = np.random.choice(
        categories[category]
    )

    product_rows.append({
        "product_id" : f"P{i:05d}",
        "product_name" : f"{sub_category} Product {i}",
        "category" : category,
        "sub_category" : sub_category
    })

products =pd.DataFrame(product_rows)

products.head()

  product_id        product_name     category sub_category
0     P00001  Skincare Product 1       Beauty     Skincare
1     P00002   Laptops Product 2  Electronics      Laptops
2     P00003  Skincare Product 3       Beauty     Skincare
3     P00004  Skincare Product 4       Beauty     Skincare
4     P00005      Bags Product 5      Fashion         Bags

In [70]:
products["price"] = np.round(
    np.random.uniform(20,2000,num_products),
    2
)

In [71]:
products.head()

  product_id        product_name     category sub_category    price
0     P00001  Skincare Product 1       Beauty     Skincare   494.89
1     P00002   Laptops Product 2  Electronics      Laptops   591.51
2     P00003  Skincare Product 3       Beauty     Skincare   632.53
3     P00004  Skincare Product 4       Beauty     Skincare  1176.05
4     P00005      Bags Product 5      Fashion         Bags   806.78

In [72]:
products["cost"] = np.round(
    products["price"] *np.random.uniform(
        0.50,0.80,num_products
    ),
    2
)

In [73]:
products.head()

  product_id        product_name     category sub_category    price    cost
0     P00001  Skincare Product 1       Beauty     Skincare   494.89  310.74
1     P00002   Laptops Product 2  Electronics      Laptops   591.51  323.53
2     P00003  Skincare Product 3       Beauty     Skincare   632.53  400.65
3     P00004  Skincare Product 4       Beauty     Skincare  1176.05  692.66
4     P00005      Bags Product 5      Fashion         Bags   806.78  499.14

In [74]:
products["profit_per_unit"] = (
    products["price"] - products["cost"]
).round(2)

In [75]:
products.head()

,product_id,product_name,category,sub_category,price,cost,profit_per_unit
0,P00001,Skincare Product 1,Beauty,Skincare,494.89,310.74,184.15
1,P00002,Laptops Product 2,Electronics,Laptops,591.51,323.53,267.98
2,P00003,Skincare Product 3,Beauty,Skincare,632.53,400.65,231.88
3,P00004,Skincare Product 4,Beauty,Skincare,1176.05,692.66,483.39
4,P00005,Bags Product 5,Fashion,Bags,806.78,499.14,307.64

 # products.to_csv(
    "../data/raw/products.csv",
    index = False
)

In [76]:
products.head(10)

,product_id,product_name,category,sub_category,price,cost,profit_per_unit
0,P00001,Skincare Product 1,Beauty,Skincare,494.89,310.74,184.15
1,P00002,Laptops Product 2,Electronics,Laptops,591.51,323.53,267.98
2,P00003,Skincare Product 3,Beauty,Skincare,632.53,400.65,231.88
3,P00004,Skincare Product 4,Beauty,Skincare,1176.05,692.66,483.39
4,P00005,Bags Product 5,Fashion,Bags,806.78,499.14,307.64
5,P00006,Haircare Product 6,Beauty,Haircare,394.20,307.44,86.76
6,P00007,Haircare Product 7,Beauty,Haircare,1952.14,1487.43,464.71
7,P00008,Outdoor Product 8,Sports,Outdoor,407.49,210.11,197.38
8,P00009,Watches Product 9,Fashion,Watches,720.71,556.25,164.46
9,P00010,Fitness Product 10,Sports,Fitness,178.45,109.30,69.15

In [77]:
products.shape

(500, 7)

# Orders.csv

In [78]:
num_orders = 20000
orders = pd.DataFrame({
        "order_id" :[f"O{i:05d}" for i in range(1,num_orders+1)],
        "customer_id" :np.random.choice(customer["customer_id"],num_orders),
        "order_status" :np.random.choice(["Delivered","Cancelled","Returned","Pending"],num_orders,p=[0.85,0.05,0.07,0.03])  
})

In [79]:
orders.head(10)

  order_id customer_id order_status
0   O00001      C02846    Delivered
1   O00002      C00980    Delivered
2   O00003      C03007    Delivered
3   O00004      C04220    Delivered
4   O00005      C04939    Delivered
5   O00006      C01292    Cancelled
6   O00007      C03425     Returned
7   O00008      C03455    Delivered
8   O00009      C01976    Delivered
9   O00010      C03562    Delivered

In [80]:
orders.shape

(20000, 3)

In [81]:
orders["customer_id"].nunique()

4894

In [82]:
orders["customer_id"].value_counts().head()

customer_id
C02994    13
C03769    12
C01927    12
C00592    12
C01983    12
Name: count, dtype: int64

In [83]:
customer.dtypes

customer_id            object
first_name             object
gender                 object
age                     int32
city                   object
country                object
signup_date    datetime64[ns]
dtype: object

In [84]:
orders.head()

  order_id customer_id order_status
0   O00001      C02846    Delivered
1   O00002      C00980    Delivered
2   O00003      C03007    Delivered
3   O00004      C04220    Delivered
4   O00005      C04939    Delivered

In [85]:
customer.head()

  customer_id first_name  gender  age       city country         signup_date
0      C00001       Emma  Female   44  Abu Dhabi     UAE 2025-12-29 22:58:08
1      C00002        Ali    Male   41  Abu Dhabi     UAE 2026-03-16 23:32:50
2      C00003   Mohammed  Female   33      Dubai     UAE 2026-06-17 00:37:09
3      C00004       John    Male   46  Abu Dhabi     UAE 2024-07-22 10:53:18
4      C00005       Emma  Female   62  Abu Dhabi     UAE 2026-06-26 10:01:17

In [91]:
orders = orders.merge(customer[["customer_id","signup_date"]],
                                    on = "customer_id",
                                    how = "left"
                                    )

In [92]:
orders.head()

  order_id customer_id order_status       signup_date_x       signup_date_y
0   O00001      C02846    Delivered 2025-09-02 07:40:39 2025-09-02 07:40:39
1   O00002      C00980    Delivered 2025-04-08 16:18:44 2025-04-08 16:18:44
2   O00003      C03007    Delivered 2024-03-04 09:27:50 2024-03-04 09:27:50
3   O00004      C04220    Delivered 2025-09-03 00:26:55 2025-09-03 00:26:55
4   O00005      C04939    Delivered 2024-10-26 05:00:10 2024-10-26 05:00:10

In [93]:
end_date = pd.Timestamp("2026-08-31")

In [94]:
orders.rename(columns={"signup_date_x":"signup_date"},inplace = True)

In [95]:
orders.drop(columns="signup_date_y",inplace=True)

In [96]:
orders.head()

  order_id customer_id order_status         signup_date
0   O00001      C02846    Delivered 2025-09-02 07:40:39
1   O00002      C00980    Delivered 2025-04-08 16:18:44
2   O00003      C03007    Delivered 2024-03-04 09:27:50
3   O00004      C04220    Delivered 2025-09-03 00:26:55
4   O00005      C04939    Delivered 2024-10-26 05:00:10

In [97]:
orders["days_available"] = (end_date - orders["signup_date"]).dt.days

In [98]:
orders.head()

  order_id customer_id order_status         signup_date  days_available
0   O00001      C02846    Delivered 2025-09-02 07:40:39             362
1   O00002      C00980    Delivered 2025-04-08 16:18:44             509
2   O00003      C03007    Delivered 2024-03-04 09:27:50             909
3   O00004      C04220    Delivered 2025-09-03 00:26:55             361
4   O00005      C04939    Delivered 2024-10-26 05:00:10             673

In [99]:
random_days = np.array([
    np.random.randint(1,days + 1)
    for days in orders["days_available"]
])

In [100]:
print(random_days)

[ 87  85 239 ... 725 110 282]

In [101]:
orders["orders_date"] = (
    orders["signup_date"]
    + pd.to_timedelta(random_days,unit="D")
)

In [102]:
orders.head()

,order_id,customer_id,order_status,signup_date,days_available,orders_date
0,O00001,C02846,Delivered,2025-09-02 07:40:39,362,2025-11-28 07:40:39
1,O00002,C00980,Delivered,2025-04-08 16:18:44,509,2025-07-02 16:18:44
2,O00003,C03007,Delivered,2024-03-04 09:27:50,909,2024-10-29 09:27:50
3,O00004,C04220,Delivered,2025-09-03 00:26:55,361,2026-02-24 00:26:55
4,O00005,C04939,Delivered,2024-10-26 05:00:10,673,2025-07-16 05:00:10

In [103]:
orders["orders_date"] = orders["orders_date"].dt.date

In [104]:
orders["signup_date"] = orders["signup_date"].dt.date

In [105]:
orders.head()

  order_id customer_id order_status signup_date  days_available orders_date
0   O00001      C02846    Delivered  2025-09-02             362  2025-11-28
1   O00002      C00980    Delivered  2025-04-08             509  2025-07-02
2   O00003      C03007    Delivered  2024-03-04             909  2024-10-29
3   O00004      C04220    Delivered  2025-09-03             361  2026-02-24
4   O00005      C04939    Delivered  2024-10-26             673  2025-07-16

In [106]:
last_names = [
    "Ahmed", "Ali", "Hassan", "Khan", "Rahman",
    "Smith", "Johnson", "Williams", "Brown", "Davis",
    "Wilson", "Taylor", "Thomas", "Moore", "Martin"
]

In [107]:
customer["last_name"] = np.random.choice(
    last_names,
    num_customers
)

In [108]:
customer["signup_date"] = customer["signup_date"].dt.date

In [109]:
customer.head()

  customer_id first_name  gender  age       city country signup_date last_name
0      C00001       Emma  Female   44  Abu Dhabi     UAE  2025-12-29     Moore
1      C00002        Ali    Male   41  Abu Dhabi     UAE  2026-03-16    Martin
2      C00003   Mohammed  Female   33      Dubai     UAE  2026-06-17   Johnson
3      C00004       John    Male   46  Abu Dhabi     UAE  2024-07-22    Rahman
4      C00005       Emma  Female   62  Abu Dhabi     UAE  2026-06-26     Ahmed

In [110]:
customer.insert(
    2,
    "last_name",
    customer.pop("last_name")
)

In [111]:
customer.head()

  customer_id first_name last_name  gender  age       city country signup_date
0      C00001       Emma     Moore  Female   44  Abu Dhabi     UAE  2025-12-29
1      C00002        Ali    Martin    Male   41  Abu Dhabi     UAE  2026-03-16
2      C00003   Mohammed   Johnson  Female   33      Dubai     UAE  2026-06-17
3      C00004       John    Rahman    Male   46  Abu Dhabi     UAE  2024-07-22
4      C00005       Emma     Ahmed  Female   62  Abu Dhabi     UAE  2026-06-26

In [112]:
customer["email"] = (
    customer["first_name"].str.lower()
    + "."
    + customer["last_name"].str.lower()
    + customer["customer_id"].str[1:]
    + "@gmail.com"                 )

In [113]:
customer.head()

,customer_id,first_name,last_name,gender,age,city,country,signup_date,email
0,C00001,Emma,Moore,Female,44,Abu Dhabi,UAE,2025-12-29,emma.moore00001@gmail.com
1,C00002,Ali,Martin,Male,41,Abu Dhabi,UAE,2026-03-16,ali.martin00002@gmail.com
2,C00003,Mohammed,Johnson,Female,33,Dubai,UAE,2026-06-17,mohammed.johnson00003@gmail.com
3,C00004,John,Rahman,Male,46,Abu Dhabi,UAE,2024-07-22,john.rahman00004@gmail.com
4,C00005,Emma,Ahmed,Female,62,Abu Dhabi,UAE,2026-06-26,emma.ahmed00005@gmail.com

In [114]:
customer.columns

Index(['customer_id', 'first_name', 'last_name', 'gender', 'age', 'city',
       'country', 'signup_date', 'email'],
      dtype='object')

In [115]:
customer.shape

(5000, 9)

In [116]:
customer["email"].is_unique

True

# customer.to_csv(
    "../data/raw/customer.csv",
    index = False
)

# orders.to_csv(
    "../data/raw/orders.csv",
    index = False
)

In [117]:
customer.head()

,customer_id,first_name,last_name,gender,age,city,country,signup_date,email
0,C00001,Emma,Moore,Female,44,Abu Dhabi,UAE,2025-12-29,emma.moore00001@gmail.com
1,C00002,Ali,Martin,Male,41,Abu Dhabi,UAE,2026-03-16,ali.martin00002@gmail.com
2,C00003,Mohammed,Johnson,Female,33,Dubai,UAE,2026-06-17,mohammed.johnson00003@gmail.com
3,C00004,John,Rahman,Male,46,Abu Dhabi,UAE,2024-07-22,john.rahman00004@gmail.com
4,C00005,Emma,Ahmed,Female,62,Abu Dhabi,UAE,2026-06-26,emma.ahmed00005@gmail.com

In [118]:
orders.head()

  order_id customer_id order_status signup_date  days_available orders_date
0   O00001      C02846    Delivered  2025-09-02             362  2025-11-28
1   O00002      C00980    Delivered  2025-04-08             509  2025-07-02
2   O00003      C03007    Delivered  2024-03-04             909  2024-10-29
3   O00004      C04220    Delivered  2025-09-03             361  2026-02-24
4   O00005      C04939    Delivered  2024-10-26             673  2025-07-16

In [119]:
orders = orders.merge(
    customer[["customer_id","city"]],
    on = "customer_id",
    how = "left"
)

In [120]:
orders.head()

,order_id,customer_id,order_status,signup_date,days_available,orders_date,city
0,O00001,C02846,Delivered,2025-09-02,362,2025-11-28,Dubai
1,O00002,C00980,Delivered,2025-04-08,509,2025-07-02,Dubai
2,O00003,C03007,Delivered,2024-03-04,909,2024-10-29,Sharjah
3,O00004,C04220,Delivered,2025-09-03,361,2026-02-24,Sharjah
4,O00005,C04939,Delivered,2024-10-26,673,2025-07-16,Sharjah

In [121]:
orders.rename(columns={"city":"shipping_city"},
              inplace = True
              )

In [122]:
orders.head()

,order_id,customer_id,order_status,signup_date,days_available,orders_date,shipping_city
0,O00001,C02846,Delivered,2025-09-02,362,2025-11-28,Dubai
1,O00002,C00980,Delivered,2025-04-08,509,2025-07-02,Dubai
2,O00003,C03007,Delivered,2024-03-04,909,2024-10-29,Sharjah
3,O00004,C04220,Delivered,2025-09-03,361,2026-02-24,Sharjah
4,O00005,C04939,Delivered,2024-10-26,673,2025-07-16,Sharjah

In [123]:
orders.drop(
    columns = ["signup_date","days_available"],
    inplace = True
)

In [124]:
orders.shape

(20000, 5)

In [125]:
orders.head()

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-28         Dubai
1   O00002      C00980    Delivered  2025-07-02         Dubai
2   O00003      C03007    Delivered  2024-10-29       Sharjah
3   O00004      C04220    Delivered  2026-02-24       Sharjah
4   O00005      C04939    Delivered  2025-07-16       Sharjah

In [126]:
print(len(orders))

20000

# Order_items.csv

In [127]:
items_per_order = np.random.randint(
    1,5,
    size = len(orders)
)

In [128]:
items_per_order[:5]

array([2, 3, 2, 2, 1], dtype=int32)

In [129]:
orders.head()

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-28         Dubai
1   O00002      C00980    Delivered  2025-07-02         Dubai
2   O00003      C03007    Delivered  2024-10-29       Sharjah
3   O00004      C04220    Delivered  2026-02-24       Sharjah
4   O00005      C04939    Delivered  2025-07-16       Sharjah

In [130]:
order_ids = np.repeat(
    orders["order_id"].values,
    items_per_order
)

In [131]:
print(order_ids)

['O00001' 'O00001' 'O00002' ... 'O19999' 'O19999' 'O20000']

In [132]:
len(order_ids)

49925

In [133]:
num_items = len(order_ids)

order_item_ids = [
    f"OI{i:06d}" for i in range(1,num_items + 1)
]

In [134]:
product_ids = np.random.choice(
    products["product_id"],
    size = num_items
)

In [135]:
quantities = np.random.randint(
    1,6,size = num_items
)

In [136]:
price_map = products.set_index(
    "product_id"
)["price"]

In [137]:
price_map

product_id
P00001     494.89
P00002     591.51
P00003     632.53
P00004    1176.05
P00005     806.78
           ...
P00496     812.27
P00497     303.39
P00498     461.36
P00499    1565.71
P00500    1147.82
Name: price, Length: 500, dtype: float64

In [138]:
unit_prices = pd.Series(product_ids).map(price_map).values

In [139]:
unit_prices

array([ 752.24, 1608.19,  405.26, ...,  108.51,  486.88,  175.57],
      shape=(49925,))

In [140]:
discounts = np.random.choice(
    [0,5,10,15,20],
    size = num_items,
    p = [0.50,0.20,0.15,0.10,0.05]
)

In [141]:
order_items = pd.DataFrame({
    "order_item_id":order_item_ids,
    "order_id":order_ids,
    "product_id":product_ids,
    "quantity":quantities,
    "unit_price":unit_prices,
    "discount":discounts
})

In [142]:
order_items.head()

  order_item_id order_id product_id  quantity  unit_price  discount
0      OI000001   O00001     P00302         3      752.24         5
1      OI000002   O00001     P00437         1     1608.19         5
2      OI000003   O00002     P00188         4      405.26        10
3      OI000004   O00002     P00446         3      328.41         0
4      OI000005   O00002     P00392         5     1258.14         0

In [143]:
order_items.shape

(49925, 6)

In [144]:
order_items["order_id"].nunique()

20000

In [145]:
order_items["gross_amount"] = (
    order_items["quantity"] * order_items["unit_price"]
).round(2)

In [146]:
order_items["discount_amount"] = (
    order_items["gross_amount"] *
    order_items["discount"] / 100
).round(2)

In [147]:
order_items["total_amount"] = (
    order_items["gross_amount"] -
    order_items["discount_amount"]
).round(2)

In [148]:
order_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount,gross_amount,discount_amount,total_amount
0,OI000001,O00001,P00302,3,752.24,5,2256.72,112.84,2143.88
1,OI000002,O00001,P00437,1,1608.19,5,1608.19,80.41,1527.78
2,OI000003,O00002,P00188,4,405.26,10,1621.04,162.10,1458.94
3,OI000004,O00002,P00446,3,328.41,0,985.23,0.00,985.23
4,OI000005,O00002,P00392,5,1258.14,0,6290.70,0.00,6290.70

In [149]:
order_items.shape

(49925, 9)

In [150]:
order_items[[
    "quantity",
    "unit_price",
    "discount",
    "gross_amount",
    "discount_amount",
    "total_amount"
]].head(10)

   quantity  unit_price  discount  gross_amount  discount_amount  total_amount
0         3      752.24         5       2256.72           112.84       2143.88
1         1     1608.19         5       1608.19            80.41       1527.78
2         4      405.26        10       1621.04           162.10       1458.94
3         3      328.41         0        985.23             0.00        985.23
4         5     1258.14         0       6290.70             0.00       6290.70
5         2      603.35         0       1206.70             0.00       1206.70
6         5     1049.27        15       5246.35           786.95       4459.40
7         3     1009.09        15       3027.27           454.09       2573.18
8         1     1375.20        15       1375.20           206.28       1168.92
9         1     1039.28         5       1039.28            51.96        987.32

In [151]:
order_items["total_amount"].min()

np.float64(17.65)

In [152]:
order_items["total_amount"].sum()

np.float64(139224122.38)

In [153]:
order_items["product_id"].isin(
    products["product_id"]
).all()

np.True_

In [154]:
order_items["order_id"].isin(
    orders["order_id"]
).all()

np.True_

In [155]:
order_items["quantity"].min()

np.int32(1)

In [156]:
order_items["quantity"].max()

np.int32(5)

In [157]:
order_items["discount"].value_counts().sort_index()

discount
0     24979
5      9987
10     7481
15     4906
20     2572
Name: count, dtype: int64

In [158]:
order_items["quantity"].sum()

np.int64(149731)

In [159]:
order_items["gross_amount"].sum().round(2)

np.float64(146549293.26)

In [160]:
order_items["discount_amount"].sum().round(2)

np.float64(7325170.88)

In [161]:
order_items["total_amount"].sum().round(2)

np.float64(139224122.38)

# order_items.to_csv(
    "order_items.csv",
    index = False
)

# Payment.csv

In [162]:
num_payments = len(orders)

In [163]:
print(num_payments)

20000

In [164]:
payment_ids = [
    f"PAY{i:06d}" for i in range(1,num_payments + 1)
]

In [165]:
payment_order_ids = orders["order_id"].values

In [166]:
print(payment_order_ids)

['O00001' 'O00002' 'O00003' ... 'O19998' 'O19999' 'O20000']

In [167]:
payment_methods = np.random.choice([
    "Credit Card",
    "Debit Card",
    "Cash on Delivery",
    "Digital Wallet",
    "Bank Transfer"
],
size = num_payments,
p = [0.30,0.25,0.20,0.20,0.05]
)

In [168]:
payment_status_map = {
    "Delivered": "Completed",
    "Cancelled": "Cancelled",
    "Returned": "Refunded",
    "Pending": "Pending"
}

In [169]:
payment_statuses = orders["order_status"].map(payment_status_map)

In [170]:
order_totals = (
    order_items
    .groupby("order_id")["total_amount"]
    .sum()
    .round(2)
)

In [171]:
print(order_totals)

order_id
O00001    3671.66
O00002    8734.87
O00003    5666.10
O00004    3742.10
O00005     987.32
           ...
O19996    9968.85
O19997    5118.87
O19998     695.30
O19999    1653.88
O20000     833.96
Name: total_amount, Length: 20000, dtype: float64

In [172]:
payment_amounts = orders["order_id"].map(
    order_totals
)

In [173]:
orders.head()

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-28         Dubai
1   O00002      C00980    Delivered  2025-07-02         Dubai
2   O00003      C03007    Delivered  2024-10-29       Sharjah
3   O00004      C04220    Delivered  2026-02-24       Sharjah
4   O00005      C04939    Delivered  2025-07-16       Sharjah

In [174]:
payment_dates = orders["orders_date"]

In [175]:
print(payment_dates)

0        2025-11-28
1        2025-07-02
2        2024-10-29
3        2026-02-24
4        2025-07-16
            ...
19995    2025-12-17
19996    2025-10-15
19997    2026-06-20
19998    2024-07-20
19999    2026-07-15
Name: orders_date, Length: 20000, dtype: object

In [176]:
payments = pd.DataFrame({
    "payment_id": payment_ids,
    "order_id": payment_order_ids,
    "payment_date": payment_dates,
    "payment_method": payment_methods,
    "payment_status": payment_statuses,
    "payment_amount": payment_amounts
})

In [177]:
payments.head()

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
0,PAY000001,O00001,2025-11-28,Digital Wallet,Completed,3671.66
1,PAY000002,O00002,2025-07-02,Cash on Delivery,Completed,8734.87
2,PAY000003,O00003,2024-10-29,Digital Wallet,Completed,5666.10
3,PAY000004,O00004,2026-02-24,Credit Card,Completed,3742.10
4,PAY000005,O00005,2025-07-16,Credit Card,Completed,987.32

In [178]:
payments.size

120000

In [179]:
payments.shape

(20000, 6)

In [180]:
payments["order_id"].nunique()

20000

In [181]:
payments["payment_id"].is_unique

True

In [182]:
payments["payment_amount"].isna().sum()

np.int64(0)

In [183]:
pd.crosstab(
    orders["order_status"],
    payments["payment_status"]
)

payment_status  Cancelled  Completed  Pending  Refunded
order_status
Cancelled            1054          0        0         0
Delivered               0      16936        0         0
Pending                 0          0      615         0
Returned                0          0        0      1395

# payments.to_csv(
    "../data/raw/payments.csv",
    index = False
)

In [184]:
print("Customers:", customer.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)

Customers: (5000, 9)
Products: (500, 7)
Orders: (20000, 5)
Order Items: (49925, 9)
Payments: (20000, 6)

In [185]:
print("CUSTOMERS")
print(customer.isna().sum())

print("\nPRODUCTS")
print(products.isna().sum())

print("\nORDERS")
print(orders.isna().sum())

print("\nORDER ITEMS")
print(order_items.isna().sum())

print("\nPAYMENTS")
print(payments.isna().sum())

CUSTOMERS
customer_id    0
first_name     0
last_name      0
gender         0
age            0
city           0
country        0
signup_date    0
email          0
dtype: int64

PRODUCTS
product_id         0
product_name       0
category           0
sub_category       0
price              0
cost               0
profit_per_unit    0
dtype: int64

ORDERS
order_id         0
customer_id      0
order_status     0
orders_date      0
shipping_city    0
dtype: int64

ORDER ITEMS
order_item_id      0
order_id           0
product_id         0
quantity           0
unit_price         0
discount           0
gross_amount       0
discount_amount    0
total_amount       0
dtype: int64

PAYMENTS
payment_id        0
order_id          0
payment_date      0
payment_method    0
payment_status    0
payment_amount    0
dtype: int64

In [186]:
customer["customer_id"].is_unique

True

In [187]:
products["product_id"].is_unique

True

In [188]:
orders["order_id"].is_unique

True

In [189]:
order_items["order_item_id"].is_unique

True

In [190]:
payments["payment_id"].is_unique

True

In [191]:
orders["customer_id"].isin(
    customer["customer_id"]
).all()

np.True_

In [192]:
order_items["order_id"].isin(
    orders["order_id"]
).all()

np.True_

In [193]:
order_items["product_id"].isin(
    products["product_id"]
).all()

np.True_

In [194]:
payments["order_id"].isin(
    orders["order_id"]
).all()

np.True_

In [195]:
order_check = orders.merge(
    customer[["customer_id", "signup_date"]],
    on="customer_id",
    how="left"
)

In [196]:
orders.head()

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-28         Dubai
1   O00002      C00980    Delivered  2025-07-02         Dubai
2   O00003      C03007    Delivered  2024-10-29       Sharjah
3   O00004      C04220    Delivered  2026-02-24       Sharjah
4   O00005      C04939    Delivered  2025-07-16       Sharjah

In [197]:
(order_check["orders_date"] > order_check["signup_date"]).all()

np.True_

In [198]:
customer["signup_date"] = pd.to_datetime(
    customer["signup_date"]
)

orders["orders_date"] = pd.to_datetime(
    orders["orders_date"]
)

payments["payment_date"] = pd.to_datetime(
    payments["payment_date"]
)

In [199]:
print(customer["signup_date"].dtype)
print(orders["orders_date"].dtype)
print(payments["payment_date"].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]

In [200]:
order_check = orders.merge(
    customer[["customer_id", "signup_date"]],
    on="customer_id",
    how="left"
)

In [201]:
print(order_check)

      order_id customer_id order_status orders_date shipping_city signup_date
0       O00001      C02846    Delivered  2025-11-28         Dubai  2025-09-02
1       O00002      C00980    Delivered  2025-07-02         Dubai  2025-04-08
2       O00003      C03007    Delivered  2024-10-29       Sharjah  2024-03-04
3       O00004      C04220    Delivered  2026-02-24       Sharjah  2025-09-03
4       O00005      C04939    Delivered  2025-07-16       Sharjah  2024-10-26
...        ...         ...          ...         ...           ...         ...
19995   O19996      C01432    Delivered  2025-12-17     Abu Dhabi  2025-10-04
19996   O19997      C04175    Delivered  2025-10-15       Sharjah  2025-03-05
19997   O19998      C04039    Delivered  2026-06-20         Dubai  2024-06-25
19998   O19999      C04214    Delivered  2024-07-20         Dubai  2024-04-01
19999   O20000      C03595    Delivered  2026-07-15     Abu Dhabi  2025-10-06

[20000 rows x 6 columns]

In [202]:
(
    order_check["orders_date"]
    > order_check["signup_date"]
).all()

np.True_

In [203]:
(
    order_check["orders_date"]
    <= pd.Timestamp("2026-08-31")
).all()

np.True_

In [209]:
customer["signup_date"] = pd.to_datetime(customer["signup_date"])
orders["orders_date"] = pd.to_datetime(orders["orders_date"])
payments["payment_date"] = pd.to_datetime(payments["payment_date"])

In [215]:
customer.to_csv("../data/raw/customer.csv", index=False)
products.to_csv("../data/raw/products.csv", index=False)
orders.to_csv("../data/raw/orders.csv", index=False)
order_items.to_csv("../data/raw/order_items.csv", index=False)
payments.to_csv("../data/raw/payments.csv", index=False)

PermissionError: [Errno 13] Permission denied: '../data/raw/customer.csv'

In [206]:
summary = pd.DataFrame({
    "Dataset": [
        "Customers",
        "Products",
        "Orders",
        "Order Items",
        "Payments"
    ],
    "Rows": [
        len(customer),
        len(products),
        len(orders),
        len(order_items),
        len(payments)
    ],
    "Columns": [
        len(customer.columns),
        len(products.columns),
        len(orders.columns),
        len(order_items.columns),
        len(payments.columns)
    ]
})

summary

       Dataset   Rows  Columns
0    Customers   5000        9
1     Products    500        7
2       Orders  20000        5
3  Order Items  49925        9
4     Payments  20000        6

In [207]:
validation_results = {
    "Customer IDs unique": customer["customer_id"].is_unique,
    "Product IDs unique": products["product_id"].is_unique,
    "Order IDs unique": orders["order_id"].is_unique,
    "Order Item IDs unique": order_items["order_item_id"].is_unique,
    "Payment IDs unique": payments["payment_id"].is_unique,

    "All order customers valid":
        orders["customer_id"].isin(customer["customer_id"]).all(),

    "All order items valid":
        order_items["order_id"].isin(orders["order_id"]).all(),

    "All products valid":
        order_items["product_id"].isin(products["product_id"]).all(),

    "All payments valid":
        payments["order_id"].isin(orders["order_id"]).all(),

    "Order dates after signup":
        (
            order_check["orders_date"]
            > order_check["signup_date"]
        ).all()
}

pd.Series(validation_results)

Customer IDs unique          True
Product IDs unique           True
Order IDs unique             True
Order Item IDs unique        True
Payment IDs unique           True
All order customers valid    True
All order items valid        True
All products valid           True
All payments valid           True
Order dates after signup     True
dtype: bool