In [37]:
import pandas as pd

# Load Five CSV Files

In [38]:
customers = pd.read_csv("../data/raw/customer.csv")

products = pd.read_csv("../data/raw/products.csv")

orders = pd.read_csv("../data/raw/orders.csv")

order_items = pd.read_csv("../data/raw/order_items.csv")

payments = pd.read_csv("../data/raw/payments.csv")

# Check the Dimensions

In [39]:
print("customers :",customers.shape)
print("products :",products.shape)
print("orders :",orders.shape)
print("order_items :",order_items.shape)
print("payments :",payments.shape)

customers : (5000, 9)
products : (500, 7)
orders : (20000, 5)
order_items : (49925, 9)
payments : (20000, 6)

# Inspecting Dataset

In [40]:
display(customers.head())
display(products.head())
display(orders.head())
display(order_items.head())
display(payments.head())

,customer_id,first_name,last_name,gender,age,city,country,signup_date,email
0,C00001,Emma,Moore,Female,44,Abu Dhabi,UAE,2025-12-29,emma.moore00001@gmail.com
1,C00002,Ali,Martin,Male,41,Abu Dhabi,UAE,2026-03-16,ali.martin00002@gmail.com
2,C00003,Mohammed,Johnson,Female,33,Dubai,UAE,2026-06-17,mohammed.johnson00003@gmail.com
3,C00004,John,Rahman,Male,46,Abu Dhabi,UAE,2024-07-22,john.rahman00004@gmail.com
4,C00005,Emma,Ahmed,Female,62,Abu Dhabi,UAE,2026-06-26,emma.ahmed00005@gmail.com

,product_id,product_name,category,sub_category,price,cost,profit_per_unit
0,P00001,Skincare Product 1,Beauty,Skincare,494.89,310.74,184.15
1,P00002,Laptops Product 2,Electronics,Laptops,591.51,323.53,267.98
2,P00003,Skincare Product 3,Beauty,Skincare,632.53,400.65,231.88
3,P00004,Skincare Product 4,Beauty,Skincare,1176.05,692.66,483.39
4,P00005,Bags Product 5,Fashion,Bags,806.78,499.14,307.64

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-28         Dubai
1   O00002      C00980    Delivered  2025-07-02         Dubai
2   O00003      C03007    Delivered  2024-10-29       Sharjah
3   O00004      C04220    Delivered  2026-02-24       Sharjah
4   O00005      C04939    Delivered  2025-07-16       Sharjah

,order_item_id,order_id,product_id,quantity,unit_price,discount,gross_amount,discount_amount,total_amount
0,OI000001,O00001,P00302,3,752.24,5,2256.72,112.84,2143.88
1,OI000002,O00001,P00437,1,1608.19,5,1608.19,80.41,1527.78
2,OI000003,O00002,P00188,4,405.26,10,1621.04,162.10,1458.94
3,OI000004,O00002,P00446,3,328.41,0,985.23,0.00,985.23
4,OI000005,O00002,P00392,5,1258.14,0,6290.70,0.00,6290.70

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
0,PAY000001,O00001,2025-11-28,Digital Wallet,Completed,3671.66
1,PAY000002,O00002,2025-07-02,Cash on Delivery,Completed,8734.87
2,PAY000003,O00003,2024-10-29,Digital Wallet,Completed,5666.10
3,PAY000004,O00004,2026-02-24,Credit Card,Completed,3742.10
4,PAY000005,O00005,2025-07-16,Credit Card,Completed,987.32

# converting the Dtype for the date column

In [44]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"])
orders["orders_date"] = pd.to_datetime(orders["orders_date"])
payments["payment_date"] = pd.to_datetime(payments["payment_date"])

# Insepect Column name and data types

In [45]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5000 non-null   object
 1   first_name   5000 non-null   object
 2   last_name    5000 non-null   object
 3   gender       5000 non-null   object
 4   age          5000 non-null   int64
 5   city         5000 non-null   object
 6   country      5000 non-null   object
 7   signup_date  5000 non-null   datetime64[ns]
 8   email        5000 non-null   object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 351.7+ KB

In [46]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_id       500 non-null    object
 1   product_name     500 non-null    object
 2   category         500 non-null    object
 3   sub_category     500 non-null    object
 4   price            500 non-null    float64
 5   cost             500 non-null    float64
 6   profit_per_unit  500 non-null    float64
dtypes: float64(3), object(4)
memory usage: 27.5+ KB

In [47]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       20000 non-null  object
 1   customer_id    20000 non-null  object
 2   order_status   20000 non-null  object
 3   orders_date    20000 non-null  datetime64[ns]
 4   shipping_city  20000 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 781.4+ KB

In [48]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49925 entries, 0 to 49924
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    49925 non-null  object
 1   order_id         49925 non-null  object
 2   product_id       49925 non-null  object
 3   quantity         49925 non-null  int64
 4   unit_price       49925 non-null  float64
 5   discount         49925 non-null  int64
 6   gross_amount     49925 non-null  float64
 7   discount_amount  49925 non-null  float64
 8   total_amount     49925 non-null  float64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.4+ MB

In [49]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      20000 non-null  object
 1   order_id        20000 non-null  object
 2   payment_date    20000 non-null  datetime64[ns]
 3   payment_method  20000 non-null  object
 4   payment_status  20000 non-null  object
 5   payment_amount  20000 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 937.6+ KB

# Checking missing values in datasets

In [50]:
datasets = {
    "Customers" : customers,
    "Products" : products,
    "Orders" : orders,
    "Order_items" : order_items,
    "Payments" : payments
}

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isna().sum())

Customers
customer_id    0
first_name     0
last_name      0
gender         0
age            0
city           0
country        0
signup_date    0
email          0
dtype: int64

Products
product_id         0
product_name       0
category           0
sub_category       0
price              0
cost               0
profit_per_unit    0
dtype: int64

Orders
order_id         0
customer_id      0
order_status     0
orders_date      0
shipping_city    0
dtype: int64

Order_items
order_item_id      0
order_id           0
product_id         0
quantity           0
unit_price         0
discount           0
gross_amount       0
discount_amount    0
total_amount       0
dtype: int64

Payments
payment_id        0
order_id          0
payment_date      0
payment_method    0
payment_status    0
payment_amount    0
dtype: int64

# Count and Calculate the percentage of missing values

In [59]:
for name, df in datasets.items():
    missing_count = df.isna().sum().sum()
    total_cell = df.size
    missing_percentage = (missing_count/total_cell) * 100

    print(f"{name} : ")
    print(f"Missing cells : {missing_count}")
    print(f"Missing percentage : {missing_percentage:.2f}%")
    print("-" * 30)

Customers :
Missing cells : 0
Missing percentage : 0.00%
------------------------------
Products :
Missing cells : 0
Missing percentage : 0.00%
------------------------------
Orders :
Missing cells : 0
Missing percentage : 0.00%
------------------------------
Order_items :
Missing cells : 0
Missing percentage : 0.00%
------------------------------
Payments :
Missing cells : 0
Missing percentage : 0.00%
------------------------------

# Detecting Duplicate Records

In [62]:
print("Customers duplicates : ",customers.duplicated().sum())
print("product duplicates : ",products.duplicated().sum())
print("Order duplicates : ",orders.duplicated().sum())
print("Order-item duplicates : ",order_items.duplicated().sum())
print("Payment duplicates : ",payments.duplicated().sum())

Customers duplicates :  0
product duplicates :  0
Order duplicates :  0
Order-item duplicates :  0
Payment duplicates :  0

In [77]:
duplicate_customers = customers[
    customers.duplicated(subset=["customer_id"], keep= False)
]

duplicate_customers

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, age, city, country, signup_date, email]
Index: []

In [78]:
duplicate_products = products[
    products.duplicated(subset=["product_id"], keep= False)
]

duplicate_products

Empty DataFrame
Columns: [product_id, product_name, category, sub_category, price, cost, profit_per_unit]
Index: []

In [79]:
duplicate_orders = orders[
    orders.duplicated(subset=["order_id"], keep= False)
]

duplicate_orders

Empty DataFrame
Columns: [order_id, customer_id, order_status, orders_date, shipping_city]
Index: []

In [88]:
duplicate_order_items = order_items[
    order_items.duplicated(subset=["order_item_id"], keep= False)
]

duplicate_order_items

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount, gross_amount, discount_amount, total_amount]
Index: []

In [83]:
duplicate_payments = payments[
    payments.duplicated(subset=["payment_id"], keep= False)
]

duplicate_payments

Empty DataFrame
Columns: [payment_id, order_id, payment_date, payment_method, payment_status, payment_amount]
Index: []

In [87]:
duplicate_orders_in_order_item = order_items[
    order_items.duplicated(subset=["order_id"], keep= False)
]

duplicate_orders_in_order_item

,order_item_id,order_id,product_id,quantity,unit_price,discount,gross_amount,discount_amount,total_amount
0,OI000001,O00001,P00302,3,752.24,5,2256.72,112.84,2143.88
1,OI000002,O00001,P00437,1,1608.19,5,1608.19,80.41,1527.78
2,OI000003,O00002,P00188,4,405.26,10,1621.04,162.10,1458.94
3,OI000004,O00002,P00446,3,328.41,0,985.23,0.00,985.23
4,OI000005,O00002,P00392,5,1258.14,0,6290.70,0.00,6290.70
...,...,...,...,...,...,...,...,...,...
49918,OI049919,O19996,P00124,4,644.10,10,2576.40,257.64,2318.76
49919,OI049920,O19997,P00477,3,790.51,20,2371.53,474.31,1897.22
49920,OI049921,O19997,P00039,5,644.33,0,3221.65,0.00,3221.65
49922,OI049923,O19999,P00145,4,108.51,5,434.04,21.70,412.34
49923,OI049924,O19999,P00017,3,486.88,15,1460.64,219.10,1241.54

In [93]:
id_checks = {
    "customers" : (customers,"customer_id"),
    "orders" : (orders,"order_id"),
    "order_items" : (order_items,"order_item_id"),
    "products" : (products,"product_id"),
    "payments" : (payments,"payment_id")
}

for name ,(df ,id_column) in id_checks.items():
    duplicate_count = df.duplicated(
        subset = [id_column],
        keep = False
    ).sum()
    print(f"{name} : {duplicate_count} rows with repeated IDs")

customers : 0 rows with repeated IDs
orders : 0 rows with repeated IDs
order_items : 0 rows with repeated IDs
products : 0 rows with repeated IDs
payments : 0 rows with repeated IDs

# Check whether IDs are Unique

In [63]:
print("Unique customer IDs : ",customers["customer_id"].is_unique)
print("Unique product IDs : ",products["product_id"].is_unique)
print("Unique order IDs : ",orders["order_id"].is_unique)
print("Unique order-item IDs : ",order_items["order_item_id"].is_unique)
print("Unique payment IDs : ",payments["payment_id"].is_unique)

Unique customer IDs :  True
Unique product IDs :  True
Unique order IDs :  True
Unique order-item IDs :  True
Unique payment IDs :  True

# Check and Clean date columns

In [100]:
print("Orders : ")
print(orders.dtypes)

print("\nPayments : ")
print(payments.dtypes)

print("\nCustomers : ")
print(customers.dtypes)

Orders :
order_id                 object
customer_id              object
order_status             object
orders_date      datetime64[ns]
shipping_city            object
dtype: object

Payments :
payment_id                object
order_id                  object
payment_date      datetime64[ns]
payment_method            object
payment_status            object
payment_amount           float64
dtype: object

Customers :
customer_id            object
first_name             object
last_name              object
gender                 object
age                     int64
city                   object
country                object
signup_date    datetime64[ns]
email                  object
dtype: object

In [102]:
print("Customer signup dates:")
display(customers[["signup_date"]].head())

print("Order dates:")
display(orders[["orders_date"]].head())

print("Payment dates:")
display(payments[["payment_date"]].head())

Customer signup dates:

  signup_date
0  2025-12-29
1  2026-03-16
2  2026-06-17
3  2024-07-22
4  2026-06-26

Order dates:

  orders_date
0  2025-11-28
1  2025-07-02
2  2024-10-29
3  2026-02-24
4  2025-07-16

Payment dates:

  payment_date
0   2025-11-28
1   2025-07-02
2   2024-10-29
3   2026-02-24
4   2025-07-16

In [104]:

customers["signup_date"] = pd.to_datetime(
    customers["signup_date"],
    errors="coerce"
)

orders["orders_date"] = pd.to_datetime(
    orders["orders_date"],
    errors="coerce"
)

payments["payment_date"] = pd.to_datetime(
    payments["payment_date"],
    errors="coerce"
)

In [107]:
print("invalid customer signup dates : ",customers["signup_date"].isna().sum())
print("invalid payment dates : ",payments["payment_date"].isna().sum())
print("invalid order dates : ",orders["orders_date"].isna().sum())

invalid customer signup dates :  0
invalid payment dates :  0
invalid order dates :  0

In [113]:

print("CUSTOMERS")
print(customers.dtypes)

print("\nORDERS")
print(orders.dtypes)

print("\nPAYMENTS")
print(payments.dtypes)

print("\nCustomer signup dates:")
display(customers[["signup_date"]].head())

print("Orders dates:")
display(orders[["orders_date"]].head())

print("Payment dates:")
display(payments[["payment_date"]].head())

CUSTOMERS
customer_id            object
first_name             object
last_name              object
gender                 object
age                     int64
city                   object
country                object
signup_date    datetime64[ns]
email                  object
dtype: object

ORDERS
order_id                 object
customer_id              object
order_status             object
orders_date      datetime64[ns]
shipping_city            object
dtype: object

PAYMENTS
payment_id                object
order_id                  object
payment_date      datetime64[ns]
payment_method            object
payment_status            object
payment_amount           float64
dtype: object

Customer signup dates:

  signup_date
0  2025-12-29
1  2026-03-16
2  2026-06-17
3  2024-07-22
4  2026-06-26

Orders dates:

  orders_date
0  2025-11-28
1  2025-07-02
2  2024-10-29
3  2026-02-24
4  2025-07-16

Payment dates:

  payment_date
0   2025-11-28
1   2025-07-02
2   2024-10-29
3   2026-02-24
4   2025-07-16

# Validate Date Relationships

In [116]:
customer_dates = customers[["customer_id","signup_date"]]

customer_dates.head()

  customer_id signup_date
0      C00001  2025-12-29
1      C00002  2026-03-16
2      C00003  2026-06-17
3      C00004  2024-07-22
4      C00005  2026-06-26

In [123]:
orders.head()

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-28         Dubai
1   O00002      C00980    Delivered  2025-07-02         Dubai
2   O00003      C03007    Delivered  2024-10-29       Sharjah
3   O00004      C04220    Delivered  2026-02-24       Sharjah
4   O00005      C04939    Delivered  2025-07-16       Sharjah

In [117]:
order_check = orders.merge(
    customer_dates,
    on="customer_id",
    how="left",
    validate="many_to_one"
)

order_check.head()

  order_id customer_id order_status orders_date shipping_city signup_date
0   O00001      C02846    Delivered  2025-11-28         Dubai  2025-09-02
1   O00002      C00980    Delivered  2025-07-02         Dubai  2025-04-08
2   O00003      C03007    Delivered  2024-10-29       Sharjah  2024-03-04
3   O00004      C04220    Delivered  2026-02-24       Sharjah  2025-09-03
4   O00005      C04939    Delivered  2025-07-16       Sharjah  2024-10-26

In [125]:
# After Merging the dataset checking for any null or mismatch
print(
    "Orders without a matching customer : ",
    order_check["signup_date"].isna().sum()  )

Orders without a matching customer :  0

In [126]:
invalid_orders = order_check[
    order_check["orders_date"] < order_check["signup_date"]
]
print("Order placed before signup : ",len(invalid_orders))

display(invalid_orders.head())

Order placed before signup :  0

Empty DataFrame
Columns: [order_id, customer_id, order_status, orders_date, shipping_city, signup_date]
Index: []

# Validate Payment Dates

In [129]:
orders.head()

  order_id customer_id order_status orders_date shipping_city
0   O00001      C02846    Delivered  2025-11-28         Dubai
1   O00002      C00980    Delivered  2025-07-02         Dubai
2   O00003      C03007    Delivered  2024-10-29       Sharjah
3   O00004      C04220    Delivered  2026-02-24       Sharjah
4   O00005      C04939    Delivered  2025-07-16       Sharjah

In [128]:
order_dates = orders[["order_id","orders_date"]]

order_dates.head()

  order_id orders_date
0   O00001  2025-11-28
1   O00002  2025-07-02
2   O00003  2024-10-29
3   O00004  2026-02-24
4   O00005  2025-07-16

In [132]:
payments_check = payments.merge(
    order_dates,
    on = "order_id",
    how = "left",
    validate = "one_to_one",
    indicator = True
)

payments_check.head()

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount,orders_date,_merge
0,PAY000001,O00001,2025-11-28,Digital Wallet,Completed,3671.66,2025-11-28,both
1,PAY000002,O00002,2025-07-02,Cash on Delivery,Completed,8734.87,2025-07-02,both
2,PAY000003,O00003,2024-10-29,Digital Wallet,Completed,5666.10,2024-10-29,both
3,PAY000004,O00004,2026-02-24,Credit Card,Completed,3742.10,2026-02-24,both
4,PAY000005,O00005,2025-07-16,Credit Card,Completed,987.32,2025-07-16,both

In [133]:
payments_check["_merge"].value_counts()

_merge
both          20000
left_only         0
right_only        0
Name: count, dtype: int64