# ShopEase — Exploratory Data Analysis

## Objective

Analyze e-commerce sales performance, customer purchasing patterns,
product categories, and revenue trends using the cleaned ShopEase dataset.

In [5]:
# import the required libraries

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [9]:
sales = pd.read_csv(
    "../data/processed/sales_analysis.csv",
    parse_dates = ["orders_date", "signup_date"]
)

print("Dataset loaded successfully!")

print("Shape : ",sales.shape)

Dataset loaded successfully!
Shape :  (49925, 26)

In [10]:
sales.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount,gross_amount,discount_amount,total_amount,customer_id,...,price,cost,profit_per_unit,first_name,last_name,gender,age,city,country,signup_date
0,OI000001,O00001,P00302,3,752.24,5,2256.72,112.84,2143.88,C02846,...,752.24,592.38,159.86,Sara,Thomas,Female,19,Dubai,UAE,2025-09-02
1,OI000002,O00001,P00437,1,1608.19,5,1608.19,80.41,1527.78,C02846,...,1608.19,838.85,769.34,Sara,Thomas,Female,19,Dubai,UAE,2025-09-02
2,OI000003,O00002,P00188,4,405.26,10,1621.04,162.10,1458.94,C00980,...,405.26,265.84,139.42,Ali,Martin,Male,36,Dubai,UAE,2025-04-08
3,OI000004,O00002,P00446,3,328.41,0,985.23,0.00,985.23,C00980,...,328.41,193.30,135.11,Ali,Martin,Male,36,Dubai,UAE,2025-04-08
4,OI000005,O00002,P00392,5,1258.14,0,6290.70,0.00,6290.70,C00980,...,1258.14,762.86,495.28,Ali,Martin,Male,36,Dubai,UAE,2025-04-08

In [11]:
sales.describe()

,quantity,unit_price,discount,gross_amount,discount_amount,total_amount,orders_date,price,cost,profit_per_unit,age,signup_date
count,49925.000000,49925.000000,49925.000000,49925.000000,49925.000000,49925.000000,49925,49925.000000,49925.000000,49925.000000,49925.000000,49925
mean,2.999119,978.485201,5.003005,2935.388949,146.723503,2788.665446,2025-12-10 20:08:31.967952,978.485201,630.996270,347.488932,40.862053,2025-03-22 15:42:16.837255
min,1.000000,22.060000,0.000000,22.060000,0.000000,17.650000,2024-01-07 00:00:00,22.060000,15.570000,6.490000,18.000000,2024-01-01 00:00:00
25%,2.000000,511.520000,0.000000,1049.270000,0.000000,997.670000,2025-08-01 00:00:00,511.520000,334.080000,168.120000,29.000000,2024-08-06 00:00:00
50%,3.000000,948.360000,0.000000,2293.300000,0.000000,2155.090000,2026-02-06 00:00:00,948.360000,599.080000,331.070000,41.000000,2025-03-20 00:00:00
75%,4.000000,1456.690000,10.000000,4312.140000,193.230000,4066.410000,2026-06-06 00:00:00,1456.690000,923.830000,502.710000,52.000000,2025-11-01 00:00:00
max,5.000000,1980.930000,20.000000,9904.650000,1980.930000,9904.650000,2026-08-30 00:00:00,1980.930000,1532.240000,954.260000,64.000000,2026-06-29 00:00:00
std,1.415219,571.277118,6.137854,2348.390054,258.924176,2243.876401,NaN,571.277118,381.567027,226.080259,13.686725,NaN

In [19]:
print("Total Rows : ",len(sales))

print(
    "Unique orders : ",
    sales["order_id"].nunique()
)

print(
    "Unique customers : ",
    sales["customer_id"].nunique()
)

print(
    "Unique products : ",
    sales["product_id"].nunique()
)

Total Rows :  49925
Unique orders :  20000
Unique customers :  4894
Unique products :  500

In [20]:
sales.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount,gross_amount,discount_amount,total_amount,customer_id,...,price,cost,profit_per_unit,first_name,last_name,gender,age,city,country,signup_date
0,OI000001,O00001,P00302,3,752.24,5,2256.72,112.84,2143.88,C02846,...,752.24,592.38,159.86,Sara,Thomas,Female,19,Dubai,UAE,2025-09-02
1,OI000002,O00001,P00437,1,1608.19,5,1608.19,80.41,1527.78,C02846,...,1608.19,838.85,769.34,Sara,Thomas,Female,19,Dubai,UAE,2025-09-02
2,OI000003,O00002,P00188,4,405.26,10,1621.04,162.10,1458.94,C00980,...,405.26,265.84,139.42,Ali,Martin,Male,36,Dubai,UAE,2025-04-08
3,OI000004,O00002,P00446,3,328.41,0,985.23,0.00,985.23,C00980,...,328.41,193.30,135.11,Ali,Martin,Male,36,Dubai,UAE,2025-04-08
4,OI000005,O00002,P00392,5,1258.14,0,6290.70,0.00,6290.70,C00980,...,1258.14,762.86,495.28,Ali,Martin,Male,36,Dubai,UAE,2025-04-08

In [22]:
# Total Revenue 

# how much sales value was generated ?

total_revenue = sales["total_amount"].sum()

print("Total recorded order value : ",round(total_revenue,2))

Total recorded order value :  139224122.38

In [25]:
# Total Orders

# How many distinct orders were placed?

total_order = sales["order_id"].nunique()

print("Total orders : ",total_order)

Total orders :  20000

In [27]:
# Calculate Average Order Value (AOV)

aov = total_revenue / total_order

print("Average Order Value : ",round(aov,2))

Average Order Value :  6961.21

In [30]:
print("================== ShopEase Business KPIs ==================")

print(f"Total Recorded order value : AED {total_revenue:,.2f}")

print(f"Total_order : {total_order:,}")

print(f"Average order value : AED {aov:,.2f}")

================== ShopEase Business KPIs ==================
Total Recorded order value : AED 139,224,122.38
Total_order : 20,000
Average order value : AED 6,961.21